theme·=·"snazzy"

[editor]
mouse·=·false
true-color·=·true
color-modes·=·true
cursorline·=·true
cursorcolumn·=·true

#·[editor.whitespace]
#·render·=·"all"
[editor.whitespace.render]
space·=·"all"
tab·=·"all"
newline·=·"none"
[editor.whitespace.characters]
space·=·"·"
nbsp·=·"⍽"
tab·=·"→"
newline·=·"⏎"
tabpad·=·"·"

[editor.indent-guides]
render·=·true
character·=·"╎"
#·Some·characters·that·work·well:·"▏",·"┆",·"┊",·"⸽"
skip-levels·=·1
