version: '3'

vars:
  task: $HOME/WorkSpace/Docker/sysinit/task/task

tasks:

  help: '{{.task}} --list-all'
  default:
    cmds:
      - task: help

  mirrors:
    - sudo wget -O /etc/pacman.d/mirrorlist
        https://www.archlinux.org/mirrorlist/?country=CN
    - sudo sed -i -e 's/^#Server/Server/g'
        /etc/pacman.d/mirrorlist

  upgrade-pacman:
    - sudo pacman -Syyu --noconfirm

  upgrade-keyring:
    - sudo pacman-key --init
    # --allow-weak-key-signatures
    - sudo pacman -Sy --noconfirm
        archlinux-keyring

  install-yay:
    - sudo pacman -Sy --noconfirm
        yay

  install-reflector:
    - yay -S --noconfirm
        reflector

  update-mirrorlist:
    - sudo reflector --verbose --country China -l 20 -p https --sort rate --save /etc/pacman.d/mirrorlist

  archlinuxcn:
    # https://mirrors.ustc.edu.cn/archlinuxcn/$arch
    # https://mirrors.bfsu.edu.cn/archlinuxcn/$arch
    # https://mirrors.nju.edu.cn/archlinuxcn/$arch
    # https://mirrors.tuna.tsinghua.edu.cn/archlinuxcn/$arch
    - if ! grep -q 'archlinuxcn' /etc/pacman.conf
      ; then
          cat /etc/pacman.conf |
            sed -e '$a\\n
              [archlinuxcn]\n
              SigLevel = Optional TrustedOnly\n
              \n
              Server = https://mirrors.tuna.tsinghua.edu.cn/archlinuxcn/$arch
            ' |
            sed -e 's/^\s*//g' |
            sudo tee /etc/pacman.conf.tmp
              > /dev/null
        ; sudo mv /etc/pacman.conf.tmp
            /etc/pacman.conf
      ; else
          echo false
      ; fi

  upgrade-keyring-cn:
    - sudo pacman-key --lsign-key "farseerfc@archlinux.org"
    - sudo pacman -Sy --noconfirm
        archlinuxcn-keyring

  upgrade-yay:
    - yay -Syyu --noconfirm

  install-paru:
    - yay -S --noconfirm
        binutils
    - yay -S --noconfirm
        paru

  upgrade-paru:
    - paru -Syyu --noconfirm

  install-base:
    - paru -S --noconfirm
        axel aria2 neovim fish
        go-task

  init-profile:
    - cat $HOME/.bashrc |
      sed -e '$a\\n
        source $HOME/.profile
      ' |
      sed -e 's/^\s*//g'
      > $HOME/.bashrc.tmp
    - mv $HOME/.bashrc.tmp
        $HOME/.bashrc
    - mkdir -p $HOME/.local/bin
    - touch $HOME/.profile
    - echo -e '
        cd $HOME\n
        export PATH=$PATH:$HOME/.local/bin
        export PODMAN_IGNORE_CGROUPSV1_WARNING=''
      ' |
      sed -e 's/^\s*//g' |
      tee $HOME/.profile
        > /dev/null

  link-local:
    - ln -s /usr/bin/nvim
        $HOME/.local/bin/vi
    - ln -s /usr/bin/nvim
        $HOME/.local/bin/vim
    - ln -s /usr/bin/go-task
        $HOME/.local/bin/task

  install-container:
    - paru -S --noconfirm
        docker podman
        docker-compose podman-compose
    - sudo usermod -aG docker $USER

    - echo "$USER:100000:65536" |
        sudo tee /etc/subuid
    - echo "$USER:100000:65536" |
        sudo tee /etc/subgid

    - sudo chmod 4755 /usr/bin/newgidmap
    - sudo chmod 4755 /usr/bin/newuidmap

  config-systemd:
    - echo -e "[boot]\nsystemd=true" |
        sudo tee -a /etc/wsl.conf

  fix-xdg:
    - sudo chown -R $USER:$USER /run/user/$(id -u $USER)

  after-container:
    - sudo systemctl enable docker
    - sudo systemctl enable podman

    - sudo systemctl restart docker
    - sudo systemctl restart podman

  all:
    cmds:
      - task: mirrors

      - task: upgrade-keyring
      - task: archlinuxcn
      - task: upgrade-keyring-cn

      - task: install-yay
      - task: install-reflector
      - task: update-mirrorlist
      - task: upgrade-pacman
      - task: upgrade-yay

      - task: install-paru
      - task: upgrade-paru

      - task: install-base
      - task: init-profile
      - task: link-local

      - task: install-container

  fix-paru:
    cmds:
      - task: install-paru
      - task: upgrade-paru

      - task: install-base
      - task: init-profile
      - task: link-local

      - task: install-container

  post:
    cmds:
      - task: fix-xdg
      - task: after-container
