version: '3'

vars:
  task: $HOME/WorkSpace/Docker/sysinit/task/task

includes:
  manjaro: ../../distro/manjaro.yml

tasks:

  help: '{{.task}} --list-all'
  default:
    - task: help

  uninstall-pre:
    - for pkg in firefox
          gedit hexchat pidgin brasero onlyoffice-desktopeditors
          uget transmission-gtk thunderbird lollypop
      ; do
        wcl=$(pacman -Q | grep "^${pkg}" | wc -l)
        ; if [[ $wcl -eq 1 ]]
        ; then
            pacman -Rsn --noconfirm $pkg
        ; fi
      ; done

  scale-hidpi:
    - paru -S --noconfirm
        mutter-x11-scaling
    - gsettings set
        org.gnome.mutter experimental-features
        "['x11-randr-fractional-scaling']"
    - xrandr --output LVDS-1 --scale 1.25x1.25

  fix-mutter:
    - sudo pacman -Syy
    - sudo pacman -Rdd
        --noconfirm
        gnome-control-center mutter
    - sudo pacman -S
        --noconfirm
        --asdeps
        budgie-control-center mutter43

  fix-webkit:
    - mv /usr/bin/WebKitWebDriver
        /usr/bin/WebKitWebDriver-5.0

  fix-paru:
    - task: manjaro:install-paru
    - task: manjaro:upgrade-paru
    - task: manjaro:install-base
    - task: manjaro:link-local
    # - task: scale-hidpi

  fix-task:
    - task: manjaro:install-base
    - task: manjaro:link-local
    # - task: scale-hidpi

  install-gui:
    - paru -S
        --noconfirm
        falkon microsoft-edge-dev-bin
        helix code wezterm zellij
        ibus ibus-rime manjaro-asian-input-support-ibus
        starship
        ulauncher
    - paru -S
        docker docker-compose
        podman podman-compose
    - sudo usermod -aG docker $USER
    - sudo systemctl enable docker.service
    - sudo systemctl restart docker.service
    - paru -S
        switchhosts-bin
    - paru -S linux61-headers rtl8814au-dkms-git
    # - paru -S
    #     switchhosts-bin

    # sudo pacman -R $(pacman -Qdtq)

    # https://github.com/otsaloma/catapult
    # - paru -S
    #     python-setuptools 
    #     catapult
    # - make build
    # - sudo make PREFIX=/usr/local install
    # - sudo ln -s /usr/bin/catapult-start
    #     /usr/local/bin/catapult-start

    # - paru -S
    #     python -launchpadlib cpu-checker

  all:
    - sudo {{.task}} manjaro:mirrors
    - sudo {{.task}} uninstall-pre

    - task: manjaro:archlinuxcn

    # - task: fix-mutter
    - task: fix-webkit

    - task: manjaro:upgrade-pacman
    - pacman-mirrors
    - task: manjaro:upgrade-keyring
    - gpgconf --kill all
    - task: manjaro:install-yay
    - task: manjaro:upgrade-yay
    - task: manjaro:install-paru
    - task: manjaro:upgrade-paru
    - task: manjaro:install-base
    - task: manjaro:link-local
    # - task: scale-hidpi
